[workspace]

members = [
  "archi"
]

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
luminance = { git = "https://github.com/phaazon/luminance-rs" }
luminance-derive = { git = "https://github.com/phaazon/luminance-rs" }
luminance-gl = { git = "https://github.com/phaazon/luminance-rs" }
