[package]
name = "archi"
version = "0.1.0"
authors = ["iwikal <e.joel.nordstrom@gmail.com>"]

[dependencies]
sdl2 = "*"
gl = "*"
glm = "*"
num = "*"
rand = "0.6"
tobj = "0.1.6"
lodepng = "2.0.0"
rgb = "0.8"
specs = "0.14.0"
specs-hierarchy = "0.3.0"
gltf = "0.11"
